export const products = [
  {
    step: "01",
    phase: "Čištění",
    name: "No1 Dvoufázová mycí emulze",
    price: "1 490 Kč",
    description: "Jemně odstraňuje nečistoty a připravuje pleť na další vrstvy rituálu.",
    usage: "Ráno i večer",
    badge: "Nejlepší první krok",
    image: "/assets/joliorigins/products/no1.png",
  },
  {
    step: "02",
    phase: "Tonizace",
    name: "No2 Bioaktivní tonikum",
    price: "1 490 Kč",
    description: "Navrací pleti pocit komfortu a připravuje ji na aplikaci aktivní péče.",
    usage: "Ráno i večer",
    badge: "Součást rituálu",
    image: "/assets/joliorigins/products/no2.png",
  },
  {
    step: "03",
    phase: "Hydratace",
    name: "No3 Collagel hydratační sérum",
    price: "2 990 Kč",
    description: "Dodává pleti pocit hydratace, plnosti a pružně působícího vzhledu.",
    usage: "Ráno i večer",
    badge: "Součást rituálu",
    image: "/assets/joliorigins/products/no3.png",
  },
  {
    step: "04",
    phase: "Denní péče",
    name: "No4 Denní vitaminové sérum + CoQ10",
    price: "3 290 Kč",
    description: "Ranní krok pro svěžejší, rozjasněnější a vitálně působící pleť.",
    usage: "Ráno",
    badge: "Ráno",
    image: "/assets/joliorigins/products/no4-day.png",
  },
  {
    step: "05",
    phase: "Noční obnova",
    name: "No5 Noční regenerační sérum",
    price: "3 490 Kč",
    description: "Večerní péče pro výživu, klid a regenerovaně působící vzhled pleti.",
    usage: "Večer",
    badge: "Večer",
    image: "/assets/joliorigins/products/no4-night.png",
  },
];

export const ritualSet = {
  name: "Generation Perfect Ritual – kompletní longevity sada",
  price: "9 000 Kč",
  rating: "4,9/5",
  reviews: 286,
  dailyPrice: "cca 98 Kč / den",
  duration: "přibližně 92 dní pravidelného používání",
};
